// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: code_generation.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCodeGenEnum int32

const (
	TestCodeGenEnum_TEST_CODE_GEN_ENUM_UNSPECIFIED TestCodeGenEnum = 0
	TestCodeGenEnum_TEST_CODE_GEN_ENUM_ANOTHER     TestCodeGenEnum = 1
)

// Enum value maps for TestCodeGenEnum.
var (
	TestCodeGenEnum_name = map[int32]string{
		0: "TEST_CODE_GEN_ENUM_UNSPECIFIED",
		1: "TEST_CODE_GEN_ENUM_ANOTHER",
	}
	TestCodeGenEnum_value = map[string]int32{
		"TEST_CODE_GEN_ENUM_UNSPECIFIED": 0,
		"TEST_CODE_GEN_ENUM_ANOTHER":     1,
	}
)

func (x TestCodeGenEnum) Enum() *TestCodeGenEnum {
	p := new(TestCodeGenEnum)
	*p = x
	return p
}

func (x TestCodeGenEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestCodeGenEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_code_generation_proto_enumTypes[0].Descriptor()
}

func (TestCodeGenEnum) Type() protoreflect.EnumType {
	return &file_code_generation_proto_enumTypes[0]
}

func (x TestCodeGenEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestCodeGenEnum.Descriptor instead.
func (TestCodeGenEnum) EnumDescriptor() ([]byte, []int) {
	return file_code_generation_proto_rawDescGZIP(), []int{0}
}

type TestCodeGenMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Double   float64                `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float    float32                `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32    int32                  `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64    int64                  `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32   uint32                 `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64   uint64                 `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32   int32                  `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64   int64                  `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32  uint32                 `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64  uint64                 `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32 int32                  `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64 int64                  `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool     bool                   `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_  string                 `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes    []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Map      map[string]int32       `protobuf:"bytes,16,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Repeated []string               `protobuf:"bytes,17,rep,name=repeated,proto3" json:"repeated,omitempty"`
	// Types that are valid to be assigned to TestCodeGenOneof:
	//
	//	*TestCodeGenMessage_AnEnum
	//	*TestCodeGenMessage_OrABoolean
	TestCodeGenOneof isTestCodeGenMessage_TestCodeGenOneof `protobuf_oneof:"TestCodeGenOneof"`
	Duration         *durationpb.Duration                  `protobuf:"bytes,20,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TestCodeGenMessage) Reset() {
	*x = TestCodeGenMessage{}
	mi := &file_code_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCodeGenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCodeGenMessage) ProtoMessage() {}

func (x *TestCodeGenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_code_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCodeGenMessage.ProtoReflect.Descriptor instead.
func (*TestCodeGenMessage) Descriptor() ([]byte, []int) {
	return file_code_generation_proto_rawDescGZIP(), []int{0}
}

func (x *TestCodeGenMessage) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *TestCodeGenMessage) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *TestCodeGenMessage) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *TestCodeGenMessage) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *TestCodeGenMessage) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *TestCodeGenMessage) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *TestCodeGenMessage) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *TestCodeGenMessage) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *TestCodeGenMessage) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *TestCodeGenMessage) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *TestCodeGenMessage) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *TestCodeGenMessage) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *TestCodeGenMessage) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *TestCodeGenMessage) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *TestCodeGenMessage) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *TestCodeGenMessage) GetMap() map[string]int32 {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *TestCodeGenMessage) GetRepeated() []string {
	if x != nil {
		return x.Repeated
	}
	return nil
}

func (x *TestCodeGenMessage) GetTestCodeGenOneof() isTestCodeGenMessage_TestCodeGenOneof {
	if x != nil {
		return x.TestCodeGenOneof
	}
	return nil
}

func (x *TestCodeGenMessage) GetAnEnum() TestCodeGenEnum {
	if x != nil {
		if x, ok := x.TestCodeGenOneof.(*TestCodeGenMessage_AnEnum); ok {
			return x.AnEnum
		}
	}
	return TestCodeGenEnum_TEST_CODE_GEN_ENUM_UNSPECIFIED
}

func (x *TestCodeGenMessage) GetOrABoolean() bool {
	if x != nil {
		if x, ok := x.TestCodeGenOneof.(*TestCodeGenMessage_OrABoolean); ok {
			return x.OrABoolean
		}
	}
	return false
}

func (x *TestCodeGenMessage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type isTestCodeGenMessage_TestCodeGenOneof interface {
	isTestCodeGenMessage_TestCodeGenOneof()
}

type TestCodeGenMessage_AnEnum struct {
	AnEnum TestCodeGenEnum `protobuf:"varint,18,opt,name=an_enum,json=anEnum,proto3,enum=example.TestCodeGenEnum,oneof"`
}

type TestCodeGenMessage_OrABoolean struct {
	OrABoolean bool `protobuf:"varint,19,opt,name=or_a_boolean,json=orABoolean,proto3,oneof"`
}

func (*TestCodeGenMessage_AnEnum) isTestCodeGenMessage_TestCodeGenOneof() {}

func (*TestCodeGenMessage_OrABoolean) isTestCodeGenMessage_TestCodeGenOneof() {}

var File_code_generation_proto protoreflect.FileDescriptor

const file_code_generation_proto_rawDesc = "" +
	"\n" +
	"\x15code_generation.proto\x12\aexample\x1a\x1egoogle/protobuf/duration.proto\"\xac\x05\n" +
	"\x12TestCodeGenMessage\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\x14\n" +
	"\x05float\x18\x02 \x01(\x02R\x05float\x12\x14\n" +
	"\x05int32\x18\x03 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x04 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x05 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x06 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\a \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\b \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\t \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\n" +
	" \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\v \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\f \x01(\x10R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytes\x126\n" +
	"\x03map\x18\x10 \x03(\v2$.example.TestCodeGenMessage.MapEntryR\x03map\x12\x1a\n" +
	"\brepeated\x18\x11 \x03(\tR\brepeated\x123\n" +
	"\aan_enum\x18\x12 \x01(\x0e2\x18.example.TestCodeGenEnumH\x00R\x06anEnum\x12\"\n" +
	"\for_a_boolean\x18\x13 \x01(\bH\x00R\n" +
	"orABoolean\x125\n" +
	"\bduration\x18\x14 \x01(\v2\x19.google.protobuf.DurationR\bduration\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x12\n" +
	"\x10TestCodeGenOneof*U\n" +
	"\x0fTestCodeGenEnum\x12\"\n" +
	"\x1eTEST_CODE_GEN_ENUM_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTEST_CODE_GEN_ENUM_ANOTHER\x10\x01B\x05P\x01Z\x01.b\x06proto3"

var (
	file_code_generation_proto_rawDescOnce sync.Once
	file_code_generation_proto_rawDescData []byte
)

func file_code_generation_proto_rawDescGZIP() []byte {
	file_code_generation_proto_rawDescOnce.Do(func() {
		file_code_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_generation_proto_rawDesc), len(file_code_generation_proto_rawDesc)))
	})
	return file_code_generation_proto_rawDescData
}

var file_code_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_generation_proto_goTypes = []any{
	(TestCodeGenEnum)(0),        // 0: example.TestCodeGenEnum
	(*TestCodeGenMessage)(nil),  // 1: example.TestCodeGenMessage
	nil,                         // 2: example.TestCodeGenMessage.MapEntry
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_code_generation_proto_depIdxs = []int32{
	2, // 0: example.TestCodeGenMessage.map:type_name -> example.TestCodeGenMessage.MapEntry
	0, // 1: example.TestCodeGenMessage.an_enum:type_name -> example.TestCodeGenEnum
	3, // 2: example.TestCodeGenMessage.duration:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_code_generation_proto_init() }
func file_code_generation_proto_init() {
	if File_code_generation_proto != nil {
		return
	}
	file_code_generation_proto_msgTypes[0].OneofWrappers = []any{
		(*TestCodeGenMessage_AnEnum)(nil),
		(*TestCodeGenMessage_OrABoolean)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_generation_proto_rawDesc), len(file_code_generation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_generation_proto_goTypes,
		DependencyIndexes: file_code_generation_proto_depIdxs,
		EnumInfos:         file_code_generation_proto_enumTypes,
		MessageInfos:      file_code_generation_proto_msgTypes,
	}.Build()
	File_code_generation_proto = out.File
	file_code_generation_proto_goTypes = nil
	file_code_generation_proto_depIdxs = nil
}
