// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/validate/custom_options.proto

package validate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldConstraints_Type int32

const (
	FieldConstraints_TYPE_UNSPECIFIED FieldConstraints_Type = 0
	FieldConstraints_TYPE_EMAIL       FieldConstraints_Type = 1
	FieldConstraints_TYPE_PHONE       FieldConstraints_Type = 2
)

// Enum value maps for FieldConstraints_Type.
var (
	FieldConstraints_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_EMAIL",
		2: "TYPE_PHONE",
	}
	FieldConstraints_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_EMAIL":       1,
		"TYPE_PHONE":       2,
	}
)

func (x FieldConstraints_Type) Enum() *FieldConstraints_Type {
	p := new(FieldConstraints_Type)
	*p = x
	return p
}

func (x FieldConstraints_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldConstraints_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_validate_custom_options_proto_enumTypes[0].Descriptor()
}

func (FieldConstraints_Type) Type() protoreflect.EnumType {
	return &file_proto_validate_custom_options_proto_enumTypes[0]
}

func (x FieldConstraints_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldConstraints_Type.Descriptor instead.
func (FieldConstraints_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_validate_custom_options_proto_rawDescGZIP(), []int{0, 0}
}

type FieldConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FieldConstraints_Type  `protobuf:"varint,2,opt,name=type,proto3,enum=validate.FieldConstraints_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldConstraints) Reset() {
	*x = FieldConstraints{}
	mi := &file_proto_validate_custom_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints) ProtoMessage() {}

func (x *FieldConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validate_custom_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints) Descriptor() ([]byte, []int) {
	return file_proto_validate_custom_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldConstraints) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldConstraints) GetType() FieldConstraints_Type {
	if x != nil {
		return x.Type
	}
	return FieldConstraints_TYPE_UNSPECIFIED
}

var file_proto_validate_custom_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*FieldConstraints)(nil),
		Field:         1188,
		Name:          "validate.field",
		Tag:           "bytes,1188,opt,name=field",
		Filename:      "proto/validate/custom_options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional validate.FieldConstraints field = 1188;
	E_Field = &file_proto_validate_custom_options_proto_extTypes[0]
)

var File_proto_validate_custom_options_proto protoreflect.FileDescriptor

const file_proto_validate_custom_options_proto_rawDesc = "" +
	"\n" +
	"#proto/validate/custom_options.proto\x12\bvalidate\x1a google/protobuf/descriptor.proto\"\x99\x01\n" +
	"\x10FieldConstraints\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.validate.FieldConstraints.TypeR\x04type\"<\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_EMAIL\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_PHONE\x10\x02:R\n" +
	"\x05field\x12\x1f.google.protobuf.MessageOptions\x18\xa4\t \x01(\v2\x1a.validate.FieldConstraintsR\x05fieldBNZLgithub.com/PacktPublishing/Protocol-Buffers-Handbook/chapter9/proto/validateb\x06proto3"

var (
	file_proto_validate_custom_options_proto_rawDescOnce sync.Once
	file_proto_validate_custom_options_proto_rawDescData []byte
)

func file_proto_validate_custom_options_proto_rawDescGZIP() []byte {
	file_proto_validate_custom_options_proto_rawDescOnce.Do(func() {
		file_proto_validate_custom_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_validate_custom_options_proto_rawDesc), len(file_proto_validate_custom_options_proto_rawDesc)))
	})
	return file_proto_validate_custom_options_proto_rawDescData
}

var file_proto_validate_custom_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_validate_custom_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_validate_custom_options_proto_goTypes = []any{
	(FieldConstraints_Type)(0),          // 0: validate.FieldConstraints.Type
	(*FieldConstraints)(nil),            // 1: validate.FieldConstraints
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_proto_validate_custom_options_proto_depIdxs = []int32{
	0, // 0: validate.FieldConstraints.type:type_name -> validate.FieldConstraints.Type
	2, // 1: validate.field:extendee -> google.protobuf.MessageOptions
	1, // 2: validate.field:type_name -> validate.FieldConstraints
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_validate_custom_options_proto_init() }
func file_proto_validate_custom_options_proto_init() {
	if File_proto_validate_custom_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_validate_custom_options_proto_rawDesc), len(file_proto_validate_custom_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_validate_custom_options_proto_goTypes,
		DependencyIndexes: file_proto_validate_custom_options_proto_depIdxs,
		EnumInfos:         file_proto_validate_custom_options_proto_enumTypes,
		MessageInfos:      file_proto_validate_custom_options_proto_msgTypes,
		ExtensionInfos:    file_proto_validate_custom_options_proto_extTypes,
	}.Build()
	File_proto_validate_custom_options_proto = out.File
	file_proto_validate_custom_options_proto_goTypes = nil
	file_proto_validate_custom_options_proto_depIdxs = nil
}
