// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto-versioning/v1/id.proto

package proto_version_go_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_proto_versioning_v1_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_proto_versioning_v1_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_proto_versioning_v1_id_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_versioning_v1_id_proto protoreflect.FileDescriptor

const file_proto_versioning_v1_id_proto_rawDesc = "" +
	"\n" +
	"\x1cproto-versioning/v1/id.proto\"\x1a\n" +
	"\x02Id\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05valueBAZ?github.com/protocol-buffers/go-proto-code/proto-version-go-codeb\x06proto3"

var (
	file_proto_versioning_v1_id_proto_rawDescOnce sync.Once
	file_proto_versioning_v1_id_proto_rawDescData []byte
)

func file_proto_versioning_v1_id_proto_rawDescGZIP() []byte {
	file_proto_versioning_v1_id_proto_rawDescOnce.Do(func() {
		file_proto_versioning_v1_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_versioning_v1_id_proto_rawDesc), len(file_proto_versioning_v1_id_proto_rawDesc)))
	})
	return file_proto_versioning_v1_id_proto_rawDescData
}

var file_proto_versioning_v1_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_versioning_v1_id_proto_goTypes = []any{
	(*Id)(nil), // 0: Id
}
var file_proto_versioning_v1_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_versioning_v1_id_proto_init() }
func file_proto_versioning_v1_id_proto_init() {
	if File_proto_versioning_v1_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_versioning_v1_id_proto_rawDesc), len(file_proto_versioning_v1_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_versioning_v1_id_proto_goTypes,
		DependencyIndexes: file_proto_versioning_v1_id_proto_depIdxs,
		MessageInfos:      file_proto_versioning_v1_id_proto_msgTypes,
	}.Build()
	File_proto_versioning_v1_id_proto = out.File
	file_proto_versioning_v1_id_proto_goTypes = nil
	file_proto_versioning_v1_id_proto_depIdxs = nil
}
