// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: wkt.proto

package hello_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_wkt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_wkt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_wkt_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_wkt_proto protoreflect.FileDescriptor

const file_wkt_proto_rawDesc = "" +
	"\n" +
	"\twkt.proto\x1a\x1egoogle/protobuf/duration.proto\"=\n" +
	"\x04Test\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bdurationB\x0fZ\rhello.packageb\x06proto3"

var (
	file_wkt_proto_rawDescOnce sync.Once
	file_wkt_proto_rawDescData []byte
)

func file_wkt_proto_rawDescGZIP() []byte {
	file_wkt_proto_rawDescOnce.Do(func() {
		file_wkt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wkt_proto_rawDesc), len(file_wkt_proto_rawDesc)))
	})
	return file_wkt_proto_rawDescData
}

var file_wkt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wkt_proto_goTypes = []any{
	(*Test)(nil),                // 0: Test
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_wkt_proto_depIdxs = []int32{
	1, // 0: Test.duration:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wkt_proto_init() }
func file_wkt_proto_init() {
	if File_wkt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wkt_proto_rawDesc), len(file_wkt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wkt_proto_goTypes,
		DependencyIndexes: file_wkt_proto_depIdxs,
		MessageInfos:      file_wkt_proto_msgTypes,
	}.Build()
	File_wkt_proto = out.File
	file_wkt_proto_goTypes = nil
	file_wkt_proto_depIdxs = nil
}
