// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto-versioning-custom/v1/field-addition-removal/field-addition-removal.proto

package proto_version_go_code_custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age   *uint64                `protobuf:"varint,2,opt,name=age,proto3,oneof" json:"age,omitempty"`
	// Removal of this field in this proto file, but another proto file contains this field then this salary is not written to the wire. Can see default value in go code
	// uint64 salary =3;
	Location string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Addition of new field, this field is ignored when not present in another proto file
	FavouriteFood *string `protobuf:"bytes,5,opt,name=favouriteFood,proto3,oneof" json:"favouriteFood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Info) GetAge() uint64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *Info) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Info) GetFavouriteFood() string {
	if x != nil && x.FavouriteFood != nil {
		return *x.FavouriteFood
	}
	return ""
}

var File_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto protoreflect.FileDescriptor

const file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDesc = "" +
	"\n" +
	"Nproto-versioning-custom/v1/field-addition-removal/field-addition-removal.proto\"\x92\x01\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x03age\x18\x02 \x01(\x04H\x00R\x03age\x88\x01\x01\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12)\n" +
	"\rfavouriteFood\x18\x05 \x01(\tH\x01R\rfavouriteFood\x88\x01\x01B\x06\n" +
	"\x04_ageB\x10\n" +
	"\x0e_favouriteFoodBHZFgithub.com/protocol-buffers/go-proto-code/proto-version-go-code-customb\x06proto3"

var (
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescOnce sync.Once
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescData []byte
)

func file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescGZIP() []byte {
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescOnce.Do(func() {
		file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDesc), len(file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDesc)))
	})
	return file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDescData
}

var file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_goTypes = []any{
	(*Info)(nil), // 0: Info
}
var file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_init()
}
func file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_init() {
	if File_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto != nil {
		return
	}
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDesc), len(file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_goTypes,
		DependencyIndexes: file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_depIdxs,
		MessageInfos:      file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_msgTypes,
	}.Build()
	File_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto = out.File
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_goTypes = nil
	file_proto_versioning_custom_v1_field_addition_removal_field_addition_removal_proto_depIdxs = nil
}
